# Generated by Django 5.0.7 on 2024-07-16 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Noodle', 'Noodle'), ('Entree', 'Entree'), ('Baking', 'Baking'), ('Hotpot', 'Hotpot'), ('Soup', 'Soup'), ('Drink', 'Drink'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
