# Generated by Django 5.0.7 on 2024-07-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_recipe_servings_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
