# Generated by Django 5.0.7 on 2024-07-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('TEASPOON', 'tsp'), ('TABLESPOON', 'tbsp'), ('CUP', 'cup'), ('PINT', 'pt'), ('QUART', 'quart'), ('GALLON', 'gallon'), ('OUNCE', 'oz'), ('FLUID OUNCE', 'fl oz'), ('POUND', 'lb'), ('MILLILITER', 'mL'), ('LITER', 'L'), ('GRAM', 'g'), ('KILOGRAM', 'kg')], max_length=15),
        ),
    ]
