# Generated by Django 5.0.7 on 2024-07-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_ingredient_quantity_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('pt', 'pt'), ('quart', 'quart'), ('gallon', 'gallon'), ('oz', 'oz'), ('fl oz', 'fl oz'), ('lb', 'lb'), ('mL', 'mL'), ('L', 'L'), ('g', 'g'), ('kg', 'kg')], max_length=15),
        ),
    ]
